test_that("contract and commons exports preserve their declared scope", {
  skip_if_not_installed("yaml")
  f <- fixture(); on.exit(cleanup(f))
  path <- file.path(f$root, "contract.yaml")
  dl_contract_yaml(f$contract, path)
  x <- yaml::read_yaml(path)
  expect_equal(x$format, "dataloom-contract")
  expect_equal(x$grain, f$contract$grain)
  expect_equal(x$key, c("id", "date"))
  expect_identical(x$allow_extra, FALSE)
  dl_commons_yaml(reserve_metric(), "published_reserves", "SUM(reserve)", path)
  x <- yaml::read_yaml(path)
  expect_equal(x$tables[[1]]$definitions[[1]]$expr, "SUM(reserve)")
  expect_error(dl_commons_yaml(reserve_metric(), "x", "SUM(x); DROP TABLE y", path), "one expression")
})

test_that("dm foreign keys reject orphaned references", {
  skip_if_not_installed("dm")
  f <- fixture(); on.exit(cleanup(f))
  dl_run(f$pipeline, f$lake)
  companies <- dl_contract("risk.company_contract", "1.0.0", "Risk", "Companies", "One company", c(company = "character"), key = "company")
  p <- dl_product("risk.companies", c(reserves = "risk.validated"),
    function(inputs) dplyr::distinct(dplyr::select(inputs$reserves, company)), companies, code_version = "v1")
  dl_build(f$lake, p)
  tables <- c(reserves = "risk.validated", companies = "risk.companies")
  keys <- list(reserves = c("id", "date"), companies = "company")
  foreign <- list(list(table = "reserves", columns = "company", ref_table = "companies", ref_columns = "company"))
  expect_s3_class(dl_model(f$lake, tables, keys, foreign), "dm")
  p$build <- function(inputs) dplyr::filter(dplyr::distinct(dplyr::select(inputs$reserves, company)), company == "Alpha")
  p$version <- "2.0.0"; p$code_version <- "v2"
  dl_build(f$lake, p)
  expect_error(dl_model(f$lake, tables, keys, foreign), class = "dl_model_invalid")
})
