#' Bind logical dbt sources to accepted RAW releases
#'
#' Write ordinary dbt source YAML pointing at immutable relations accepted by
#' [ingest()]. Logical names stay the same when a later call explicitly selects
#' a newer release. No data, views or dbt seeds are written.
#'
#' Every result must be successful, belong to the same catalog, and contain a
#' qualified RAW output reference. The entire batch is validated before writing.
#' Existing bindings with other logical names are retained. Only the generated
#' `models/tidyweave_sources_<name>.yml` file is replaced, using a temporary file
#' in the same directory. An existing file without the ownership marker is
#' never overwritten. Coordinate concurrent project writers yourself.
#'
#' The profile must attach that catalog under the recorded database name
#' (normally `lake`). Projects created with [dbt_init()] also check the catalog
#' against their stored configuration. For externally configured projects,
#' matching profile attachments remain the caller's responsibility.
#'
#' @param project A [dbt_project()] specification.
#' @param sources Named, non-empty list of successful `tw_run_result` objects
#'   returned by [ingest()]. Names are dbt identifiers such as `orders`.
#' @param name Logical dbt source name, used by `source(name, table)` in SQL.
#' @returns The project specification, invisibly, for use in a pipe.
#' @seealso [dbt_init()], [dbt_contract()]
#' @examplesIf requireNamespace("duckdb", quietly = TRUE) && requireNamespace("yaml", quietly = TRUE)
#' root <- tempfile("tidyweave-dbt-sources-")
#' config <- lake_config(
#'   registry_duckdb(file.path(root, "lake.db")),
#'   storage_local(file.path(root, "data")),
#'   landing = file.path(root, "landing"), backend = "duckdb",
#'   layers = c("raw", "staging", "core", "marts")
#' )
#' accepted <- ingest(config, data.frame(
#'   order_id = 1:2, customer_id = c(1L, 1L), amount = c(10, 20)
#' ), "orders")
#' project <- dbt_init(file.path(root, "dbt"), config,
#'   sources = list(orders = accepted))
#' dbt_sources(project, list(orders = accepted))
#' unlink(root, recursive = TRUE)
#' @export
dbt_sources <- function(project, sources, name = "raw") {
  need("yaml")
  if (!inherits(project, "tw_dbt_project")) {
    abort("Use dbt_project() or dbt_init() first.", "tw_dbt_invalid")
  }
  ident(name)
  binding <- dbt_source_binding(sources, name)
  if (!file.exists(file.path(project$path, "dbt_project.yml"))) {
    abort("No dbt_project.yml found in the project.", "tw_dbt_invalid")
  }
  if (!is.null(project$source_config)) {
    expected <- dbt_catalog_fingerprint(project$source_config)
    if (!identical(binding$config$meta$tidyweave$catalog, expected)) {
      abort(
        "RAW sources belong to a different project catalog.",
        "tw_dbt_invalid"
      )
    }
  }
  directory <- file.path(project$path, "models")
  destination <- file.path(
    directory,
    paste0("tidyweave_sources_", name, ".yml")
  )
  marker <- "# Generated by tidyweave::dbt_sources."
  if (file.exists(destination)) {
    if (!identical(readLines(destination, n = 1L, warn = FALSE), marker)) {
      abort(
        "The source YAML is not package-owned; choose another source name.",
        "tw_dbt_invalid"
      )
    }
    previous <- tryCatch(yaml::read_yaml(destination), error = identity)
    old <- if (is.list(previous) && length(previous$sources) == 1L) {
      previous$sources[[1L]]
    } else {
      NULL
    }
    if (
      !is.list(old) ||
        !identical(old$name, name) ||
        !is.list(old$tables) ||
        !identical(old$database, binding$database) ||
        !identical(old$schema, binding$schema) ||
        !identical(
          old$config$meta$tidyweave$catalog,
          binding$config$meta$tidyweave$catalog
        )
    ) {
      abort(
        "Existing source YAML is invalid or belongs to another catalog.",
        "tw_dbt_invalid"
      )
    }
    old_names <- vapply(
      old$tables,
      function(table) {
        if (
          !is.list(table) ||
            !is.character(table$name) ||
            length(table$name) != 1L ||
            is.na(table$name)
        ) {
          return(NA_character_)
        }
        table$name
      },
      character(1)
    )
    if (anyNA(old_names) || anyDuplicated(old_names)) {
      abort(
        "Existing source YAML contains invalid table names.",
        "tw_dbt_invalid"
      )
    }
    new_names <- vapply(binding$tables, `[[`, character(1), "name")
    binding$tables <- c(old$tables[!old_names %in% new_names], binding$tables)
  }
  content <- paste0(
    marker,
    "\n",
    yaml::as.yaml(list(
      version = 2L,
      sources = list(binding)
    ))
  )
  if (
    !dir.exists(directory) &&
      !dir.create(directory, recursive = TRUE, showWarnings = FALSE)
  ) {
    abort("Cannot create the dbt models directory.", "tw_dbt_io")
  }
  temporary <- tempfile(".tidyweave-sources-", tmpdir = directory)
  on.exit(unlink(temporary), add = TRUE)
  writeLines(content, temporary, useBytes = TRUE)
  if (!suppressWarnings(file.rename(temporary, destination))) {
    abort(
      "Could not replace source YAML; the previous file was preserved.",
      "tw_dbt_io"
    )
  }
  invisible(project)
}

dbt_catalog_fingerprint <- function(config) {
  if (!inherits(config, "tw_config")) {
    abort("A RAW release must retain its lake configuration.", "tw_dbt_invalid")
  }
  fingerprint(list(
    backend = config$backend,
    catalog = config$catalog,
    storage = if (identical(config$backend, "ducklake")) {
      config$storage
    } else {
      NULL
    }
  ))
}

dbt_source_binding <- function(sources, name = "raw") {
  if (
    !is.list(sources) ||
      !length(sources) ||
      is.null(names(sources)) ||
      anyNA(names(sources)) ||
      anyDuplicated(names(sources)) ||
      any(!nzchar(names(sources)))
  ) {
    abort(
      "sources must be a named, non-empty list of accepted RAW results.",
      "tw_dbt_invalid"
    )
  }
  invisible(lapply(names(sources), ident))
  catalog <- database <- NULL
  tables <- lapply(seq_along(sources), function(index) {
    result <- sources[[index]]
    label <- names(sources)[[index]]
    invalid <- function() {
      abort(
        paste0(
          "Source `",
          label,
          "` needs a successful, qualified immutable RAW release from ingest()."
        ),
        "tw_dbt_invalid"
      )
    }
    if (
      !inherits(result, "tw_run_result") ||
        !is.character(result$status) ||
        length(result$status) != 1L ||
        is.na(result$status) ||
        !result$status %in% c("published", "cached") ||
        !is.list(result$outputs)
    ) {
      invalid()
    }
    reference <- result$outputs
    fields <- c("database", "schema", "table", "asset", "release_id")
    valid <- vapply(
      reference[fields],
      function(value) {
        is.character(value) &&
          length(value) == 1L &&
          !is.na(value) &&
          nzchar(value)
      },
      logical(1)
    )
    if (
      !all(valid) ||
        !identical(reference$type, "lake release") ||
        !identical(reference$schema, "raw") ||
        !identical(reference$asset, result$asset) ||
        !identical(reference$release_id, result$release_id) ||
        !is.character(result$run_id) ||
        length(result$run_id) != 1L ||
        is.na(result$run_id) ||
        !nzchar(result$run_id)
    ) {
      invalid()
    }
    current <- dbt_catalog_fingerprint(result$output_config)
    if (is.null(catalog)) {
      catalog <<- current
      database <<- reference$database
    }
    if (
      !identical(catalog, current) || !identical(database, reference$database)
    ) {
      abort(
        "All source bindings must belong to the same catalog and database.",
        "tw_dbt_invalid"
      )
    }
    list(
      name = label,
      identifier = reference$table,
      description = paste("Accepted RAW release of", reference$asset),
      config = list(
        meta = list(
          tidyweave = list(
            asset = reference$asset,
            release_id = reference$release_id,
            run_id = result$run_id,
            status = result$status
          )
        )
      )
    )
  })
  list(
    name = name,
    database = database,
    schema = "raw",
    quoting = list(database = TRUE, schema = TRUE, identifier = TRUE),
    config = list(meta = list(tidyweave = list(catalog = catalog))),
    tables = tables
  )
}
